spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:http://localhost:8888


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
