spring:
  application:
    name: acitivity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: fitnessActivity

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/