spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: fitnessrecommendation

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
