spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: fitnessActivity
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
